steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ts-cloud-factory-poc/github.com/santosh-sahoo334/mindsdb:${COMMIT_SHA}','-f','./docker/Dockerfile','.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ts-cloud-factory-poc/github.com/santosh-sahoo334/mindsdb:${COMMIT_SHA}']
timeout: 9000s
options:
 machineType: N1_HIGHCPU_32
#  Disk Size
 diskSizeGb: 100